# Generated by Django 4.2.7 on 2023-11-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('engineCapacity', models.IntegerField()),
                ('engineType', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('hybryda', 'Hybryda'), ('elektryczny', 'Elektryczny')], max_length=16)),
                ('gear', models.CharField(max_length=16)),
                ('drive_train', models.CharField(choices=[('przednionapęd', 'Przedni napęd'), ('tylnionapęd', 'Tylni napęd'), ('napęd4x4', 'Napęd 4x4')], max_length=16)),
                ('doors', models.IntegerField()),
            ],
        ),
    ]
