# Generated by Django 4.2.7 on 2023-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('manulany', 'Manualny'), ('automatyczny', 'Automatyczny')], max_length=16),
        ),
    ]
