# Generated by Django 4.2.7 on 2023-11-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody_web', '0002_alter_car_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
